export const COUNTRY_NAMES = {
  AR: 'Argentina',
  BR: 'Brasil',
  MX: 'México',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Perú',
  UY: 'Uruguay',
  ES: 'España',
  US: 'Estados Unidos',
  GB: 'Reino Unido',
}

export const COUNTRY_LOGOS = {
  AR: [
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.svg' },
    { name: 'Globant',       logo: '/logos/globant.png' },
    { name: 'Ualá',          logo: '/logos/uala.png' },
    { name: 'Galicia',       logo: '/logos/galicia.png' },
    { name: 'YPF',           logo: '/logos/ypf.png' },
    { name: 'Despegar',      logo: '/logos/despegar.png' },
    { name: 'NaranjaX',     logo: '/logos/naranjax.png' },
    { name: 'PedidosYa',    logo: '/logos/pedidosya.png' },
  ],
  BR: [
    { name: 'Nubank',         logo: '/logos/nubank.png' },
    { name: 'iFood',          logo: '/logos/ifood.png' },
    { name: 'Itaú',           logo: '/logos/itau.png' },
    { name: 'Magazine Luiza', logo: '/logos/magazineluiza.png' },
    { name: 'Rappi',          logo: '/logos/rappi.png' },
    { name: 'Mercado Libre',  logo: '/logos/mercadolibre.svg' },
    { name: 'Amazon',         logo: '/logos/amazon.png' },
  ],
  MX: [
    { name: 'OXXO',          logo: '/logos/oxxo.png' },
    { name: 'Telcel',        logo: '/logos/telcel.png' },
    { name: 'América Móvil', logo: '/logos/americamovil.png' },
    { name: 'Walmart',       logo: '/logos/walmart.png' },
    { name: 'FEMSA',         logo: '/logos/femsa.png' },
    { name: 'Coppel',        logo: '/logos/coppel.png' },
    { name: 'Grupo Bimbo',  logo: '/logos/grupobimbo.png' },
    { name: 'Rappi',         logo: '/logos/rappi.png' },
    { name: 'Amazon',        logo: '/logos/amazon.png' },
  ],
  CO: [
    { name: 'Bancolombia',   logo: '/logos/bancolombia.png' },
    { name: 'Rappi',         logo: '/logos/rappi.png' },
    { name: 'Davivienda',    logo: '/logos/davivienda.png' },
    { name: 'Nubank',        logo: '/logos/nubank.png' },
    { name: 'iFood',         logo: '/logos/ifood.png' },
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.svg' },
  ],
  CL: [
    { name: 'Falabella', logo: '/logos/falabella.png' },
    { name: 'Entel',     logo: '/logos/entel.png' },
    { name: 'Cencosud',  logo: '/logos/cencosud.png' },
    { name: 'Ripley',    logo: '/logos/ripley.png' },
    { name: 'Rappi',     logo: '/logos/rappi.png' },
    { name: 'Walmart',   logo: '/logos/walmart.png' },
  ],
  PE: [
    { name: 'Yape',          logo: '/logos/yape.png' },
    { name: 'Rappi',         logo: '/logos/rappi.png' },
    { name: 'Falabella',     logo: '/logos/falabella.png' },
    { name: 'Nubank',        logo: '/logos/nubank.png' },
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.svg' },
  ],
  UY: [
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.svg' },
    { name: 'Rappi',         logo: '/logos/rappi.png' },
    { name: 'Despegar',      logo: '/logos/despegar.png' },
    { name: 'PedidosYa',    logo: '/logos/pedidosya.png' },
    { name: 'Globant',       logo: '/logos/globant.png' },
  ],
  ES: [
    { name: 'Santander',  logo: '/logos/santander.png' },
    { name: 'BBVA',       logo: '/logos/bbva.png' },
    { name: 'Inditex',    logo: '/logos/inditex.png' },
    { name: 'Telefónica', logo: '/logos/telefonica.png' },
    { name: 'Cencosud',   logo: '/logos/cencosud.png' },
  ],
  US: [
    { name: 'Google',    logo: '/logos/google.png' },
    { name: 'Amazon',    logo: '/logos/amazon.png' },
    { name: 'Microsoft', logo: '/logos/microsoft.png' },
    { name: 'Meta',      logo: '/logos/meta.png' },
    { name: 'Apple',     logo: '/logos/apple.png' },
    { name: 'Netflix',   logo: '/logos/netflix.png' },
    { name: 'Spotify',   logo: '/logos/spotify.png' },
    { name: 'Stripe',    logo: '/logos/stripe.png' },
  ],
  GB: [
    { name: 'Google',    logo: '/logos/google.png' },
    { name: 'Amazon',    logo: '/logos/amazon.png' },
    { name: 'Microsoft', logo: '/logos/microsoft.png' },
    { name: 'Spotify',   logo: '/logos/spotify.png' },
    { name: 'Stripe',    logo: '/logos/stripe.png' },
  ],
  DEFAULT: [
    { name: 'Google',    logo: '/logos/google.png' },
    { name: 'Amazon',    logo: '/logos/amazon.png' },
    { name: 'Microsoft', logo: '/logos/microsoft.png' },
    { name: 'Meta',      logo: '/logos/meta.png' },
    { name: 'Apple',     logo: '/logos/apple.png' },
    { name: 'Netflix',   logo: '/logos/netflix.png' },
    { name: 'Spotify',   logo: '/logos/spotify.png' },
    { name: 'Stripe',    logo: '/logos/stripe.png' },
  ],
}
