// logo: path local al SVG real | null si no hay ícono oficial
// color: color corporativo (para el dot de fallback)
export const COUNTRY_NAMES = {
  AR: 'Argentina',
  BR: 'Brasil',
  MX: 'México',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Perú',
  UY: 'Uruguay',
  ES: 'España',
  US: 'Estados Unidos',
  GB: 'Reino Unido',
}

export const COUNTRY_LOGOS = {
  AR: [
    { name: 'Mercado Libre', logo: null,                   color: '#FFE600' },
    { name: 'Globant',       logo: null,                   color: '#97CF00' },
    { name: 'Ualá',          logo: null,                   color: '#C040E8' },
    { name: 'Galicia',       logo: null,                   color: '#E30613' },
    { name: 'YPF',           logo: null,                   color: '#00A6E6' },
    { name: 'Despegar',      logo: null,                   color: '#F15A22' },
    { name: 'NaranjaX',      logo: null,                   color: '#F37021' },
    { name: 'PedidosYa',     logo: null,                   color: '#FA0050' },
  ],
  BR: [
    { name: 'Nubank',         logo: '/logos/nubank.svg',   color: '#820AD1' },
    { name: 'iFood',          logo: '/logos/ifood.svg',    color: '#EA1D2C' },
    { name: 'Itaú',           logo: null,                  color: '#EC7000' },
    { name: 'Magazine Luiza', logo: null,                  color: '#0086FF' },
    { name: 'Rappi',          logo: null,                  color: '#FF441F' },
    { name: 'Ambev',          logo: null,                  color: '#F7A600' },
  ],
  MX: [
    { name: 'OXXO',        logo: null,                    color: '#E31E24' },
    { name: 'Cemex',       logo: null,                    color: '#005DAA' },
    { name: 'Banorte',     logo: null,                    color: '#C8102E' },
    { name: 'Grupo Bimbo', logo: null,                    color: '#0057A8' },
    { name: 'Rappi',       logo: null,                    color: '#FF441F' },
    { name: 'Liverpool',   logo: null,                    color: '#C41230' },
  ],
  CO: [
    { name: 'Bancolombia', logo: null,                    color: '#FDDA24' },
    { name: 'Rappi',       logo: null,                    color: '#FF441F' },
    { name: 'Davivienda',  logo: null,                    color: '#DA0000' },
    { name: 'Nubank',      logo: '/logos/nubank.svg',     color: '#820AD1' },
    { name: 'iFood',       logo: '/logos/ifood.svg',      color: '#EA1D2C' },
  ],
  CL: [
    { name: 'Falabella', logo: null,                      color: '#79B700' },
    { name: 'Entel',     logo: null,                      color: '#00539B' },
    { name: 'Cencosud',  logo: null,                      color: '#005BAA' },
    { name: 'Ripley',    logo: null,                      color: '#7C1E6F' },
    { name: 'Rappi',     logo: null,                      color: '#FF441F' },
  ],
  PE: [
    { name: 'Yape',      logo: null,                      color: '#6B1BE3' },
    { name: 'Rappi',     logo: null,                      color: '#FF441F' },
    { name: 'Falabella', logo: null,                      color: '#79B700' },
    { name: 'Nubank',    logo: '/logos/nubank.svg',       color: '#820AD1' },
  ],
  UY: [
    { name: 'Mercado Libre', logo: null,                  color: '#FFE600' },
    { name: 'Rappi',         logo: null,                  color: '#FF441F' },
    { name: 'Despegar',      logo: null,                  color: '#F15A22' },
    { name: 'PedidosYa',     logo: null,                  color: '#FA0050' },
    { name: 'Globant',       logo: null,                  color: '#97CF00' },
  ],
  ES: [
    { name: 'Santander',  logo: null,                     color: '#EC0000' },
    { name: 'BBVA',       logo: null,                     color: '#004481' },
    { name: 'Inditex',    logo: null,                     color: '#1a1a1a' },
    { name: 'Telefónica', logo: '/logos/telefonica.svg',  color: '#0066FF' },
    { name: 'Iberdrola',  logo: null,                     color: '#006A35' },
  ],
  US: [
    { name: 'Google',    logo: '/logos/google.svg',       color: '#4285F4' },
    { name: 'Amazon',    logo: '/logos/amazon.svg',       color: '#FF9900' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg',    color: '#00A4EF' },
    { name: 'Meta',      logo: '/logos/meta.svg',         color: '#0082FB' },
    { name: 'Apple',     logo: '/logos/apple.svg',        color: '#555555' },
    { name: 'Netflix',   logo: '/logos/netflix.svg',      color: '#E50914' },
    { name: 'Spotify',   logo: '/logos/spotify.svg',      color: '#1DB954' },
    { name: 'Stripe',    logo: '/logos/stripe.svg',       color: '#635BFF' },
  ],
  GB: [
    { name: 'Google',    logo: '/logos/google.svg',       color: '#4285F4' },
    { name: 'Amazon',    logo: '/logos/amazon.svg',       color: '#FF9900' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg',    color: '#00A4EF' },
    { name: 'Spotify',   logo: '/logos/spotify.svg',      color: '#1DB954' },
    { name: 'Stripe',    logo: '/logos/stripe.svg',       color: '#635BFF' },
  ],
  DEFAULT: [
    { name: 'Google',    logo: '/logos/google.svg',       color: '#4285F4' },
    { name: 'Amazon',    logo: '/logos/amazon.svg',       color: '#FF9900' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg',    color: '#00A4EF' },
    { name: 'Meta',      logo: '/logos/meta.svg',         color: '#0082FB' },
    { name: 'Apple',     logo: '/logos/apple.svg',        color: '#555555' },
    { name: 'Netflix',   logo: '/logos/netflix.svg',      color: '#E50914' },
    { name: 'Spotify',   logo: '/logos/spotify.svg',      color: '#1DB954' },
    { name: 'Stripe',    logo: '/logos/stripe.svg',       color: '#635BFF' },
  ],
}
