export const COUNTRY_NAMES = {
  AR: 'Argentina',
  BR: 'Brasil',
  MX: 'México',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Perú',
  UY: 'Uruguay',
  ES: 'España',
  US: 'Estados Unidos',
  GB: 'Reino Unido',
}

export const COUNTRY_LOGOS = {
  AR: [
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.png' },
    { name: 'Globant',       logo: '/logos/globant.png' },
    { name: 'Ualá',          logo: '/logos/uala.png' },
    { name: 'Galicia',       logo: '/logos/galicia.png' },
    { name: 'YPF',           logo: '/logos/ypf.png' },
    { name: 'Despegar',      logo: '/logos/despegar.png' },
    { name: 'NaranjaX',     logo: '/logos/naranjax.png' },
    { name: 'PedidosYa',    logo: '/logos/pedidosya.png' },
  ],
  BR: [
    { name: 'Nubank',         logo: '/logos/nubank.png' },
    { name: 'iFood',          logo: '/logos/ifood.png' },
    { name: 'Itaú',           logo: '/logos/itau.png' },
    { name: 'Magazine Luiza', logo: '/logos/magazineluiza.png' },
    { name: 'Rappi',          logo: '/logos/rappi.png' },
  ],
  MX: [
    { name: 'Rappi',       logo: '/logos/rappi.png' },
    { name: 'Santander',   logo: '/logos/santander.png' },
    { name: 'BBVA',        logo: '/logos/bbva.png' },
    { name: 'Inditex',     logo: '/logos/inditex.png' },
    { name: 'Falabella',   logo: '/logos/falabella.png' },
  ],
  CO: [
    { name: 'Bancolombia', logo: '/logos/bancolombia.png' },
    { name: 'Rappi',       logo: '/logos/rappi.png' },
    { name: 'Nubank',      logo: '/logos/nubank.png' },
    { name: 'Falabella',   logo: '/logos/falabella.png' },
  ],
  CL: [
    { name: 'Falabella', logo: '/logos/falabella.png' },
    { name: 'Entel',     logo: '/logos/entel.png' },
    { name: 'Cencosud',  logo: '/logos/cencosud.png' },
    { name: 'Rappi',     logo: '/logos/rappi.png' },
  ],
  PE: [
    { name: 'Yape',      logo: '/logos/yape.png' },
    { name: 'Rappi',     logo: '/logos/rappi.png' },
    { name: 'Falabella', logo: '/logos/falabella.png' },
    { name: 'Nubank',    logo: '/logos/nubank.png' },
  ],
  UY: [
    { name: 'Mercado Libre', logo: '/logos/mercadolibre.png' },
    { name: 'Rappi',         logo: '/logos/rappi.png' },
    { name: 'Despegar',      logo: '/logos/despegar.png' },
    { name: 'PedidosYa',    logo: '/logos/pedidosya.png' },
    { name: 'Globant',       logo: '/logos/globant.png' },
  ],
  ES: [
    { name: 'Santander',  logo: '/logos/santander.png' },
    { name: 'BBVA',       logo: '/logos/bbva.png' },
    { name: 'Inditex',    logo: '/logos/inditex.png' },
    { name: 'Telefónica', logo: '/logos/telefonica.svg' },
    { name: 'Cencosud',   logo: '/logos/cencosud.png' },
  ],
  US: [
    { name: 'Google',    logo: '/logos/google.svg' },
    { name: 'Amazon',    logo: '/logos/amazon.svg' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg' },
    { name: 'Meta',      logo: '/logos/meta.svg' },
    { name: 'Apple',     logo: '/logos/apple.svg' },
    { name: 'Netflix',   logo: '/logos/netflix.svg' },
    { name: 'Spotify',   logo: '/logos/spotify.svg' },
    { name: 'Stripe',    logo: '/logos/stripe.svg' },
  ],
  GB: [
    { name: 'Google',    logo: '/logos/google.svg' },
    { name: 'Amazon',    logo: '/logos/amazon.svg' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg' },
    { name: 'Spotify',   logo: '/logos/spotify.svg' },
    { name: 'Stripe',    logo: '/logos/stripe.svg' },
  ],
  DEFAULT: [
    { name: 'Google',    logo: '/logos/google.svg' },
    { name: 'Amazon',    logo: '/logos/amazon.svg' },
    { name: 'Microsoft', logo: '/logos/microsoft.svg' },
    { name: 'Meta',      logo: '/logos/meta.svg' },
    { name: 'Apple',     logo: '/logos/apple.svg' },
    { name: 'Netflix',   logo: '/logos/netflix.svg' },
    { name: 'Spotify',   logo: '/logos/spotify.svg' },
    { name: 'Stripe',    logo: '/logos/stripe.svg' },
  ],
}
